(in-package :mu-cl-resources)

(setf *supply-cache-headers-p* t)

(define-resource pillar ()
  :class (s-prefix "esco:ConceptScheme")
  :properties `((:preflabel :string-set ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://data.europa.eu/esco/concept-scheme/")
  :has-many `((concept :via ,(s-prefix "skos:topConceptOf")
                     :inverse t
                     :as "top-concepts")
              (structure :via ,(s-prefix "esco:structureFor")
                      :inverse t
                      :as "structures"))
  :on-path "taxonomies")

(define-resource concept-scheme ()
  :class (s-prefix "skos:ConceptScheme")
  :properties `((:preflabel :string-set ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://data.europa.eu/esco/concept-scheme/")
  :has-many `((concept :via ,(s-prefix "skos:topConceptOf")
                     :inverse t
                     :as "top-concepts"))
  :on-path "concept-schemes")

(define-resource structure ()
  :class (s-prefix "esco:Structure")
  :properties `((:name :string ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description"))
                (:coded-property :uri ,(s-prefix "esco:codedProperty"))
                (:default :string ,(s-prefix "esco:is-default-structure"))
                (:disabled :string ,(s-prefix "esco:is-disabled")))
  :has-one `((pillar :via ,(s-prefix "esco:structureFor")
                      :as "pillar")
            (concept-scheme :via ,(s-prefix "esco:codeList")
                                  :as "code-list"))
  :resource-base (s-url "http://mu.semte.ch/vocabularies/hierarchy/")
  :on-path "structures")

(define-resource concept ()
  :class (s-prefix "skos:Concept")
  :properties `((:codes :string-set ,(s-prefix "dcterms:identifier"))
                (:types :uri-set ,(s-prefix "rdf:type"))
                (:description :language-string-set ,(s-prefix "dcterms:description"))
                (:scope-note :language-string-set ,(s-prefix "skos:scopeNote"))
                (:definition :language-string-set ,(s-prefix "skos:definition"))
                (:skill-type :uri-set ,(s-prefix "esco:skillType"))
                (:last-modified :string ,(s-prefix "esco:last-modified")))
  :features '(no-pagination-defaults)
  :resource-base (s-url "http://translation.escoportal.eu/concept/")
  :has-one `((concept :via ,(s-prefix "esco:memberOfISCOGroup")
                     :as "isco"))
  :has-many `((concept-label :via ,(s-prefix "skosxl:altLabel")
                     :as "alt-labels")
			  (concept-label :via ,(s-prefix "skosxl:hiddenLabel")
                     :as "hidden-labels")
			  (concept-label :via ,(s-prefix "skosxl:prefLabel")
                     :as "pref-labels")
			  (concept :via ,(s-prefix "skos:broader")
                     :inverse t
                     :as "narrower")
			  (concept :via ,(s-prefix "skos:broader")
                     :as "broader")
        (concept :via ,(s-prefix "esco:hasNACECode")
                     :as "nace")
			  (concept :via ,(s-prefix "mu:replacedBy")
                     :inverse t
                     :as "replaces")
        (concept :via ,(s-prefix "mu:replacedBy")
                     :as "replacements")
        (concept-relation :via ,(s-prefix "esco:isRelationshipFor")
                     :inverse t
                     :as "relations")
        (concept-relation :via ,(s-prefix "esco:refersConcept")
                     :inverse t
                     :as "inverse-relations")
			  (concept-scheme :via ,(s-prefix "skos:inScheme")
                     :as "taxonomies")
			  (concept-scheme :via ,(s-prefix "skos:topConceptOf")
                     :as "top-concept-of"))
  :on-path "concepts")

(define-resource concept-label ()
  :class (s-prefix "skosxl:Label")
  :properties `((:literal-form-values :language-string-set ,(s-prefix "skosxl:literalForm")))
  :resource-base (s-url "http://visualization-tool.sem.tenforce.com/label/")
  :features '(no-pagination-defaults)
  :has-many `((label-role :via ,(s-prefix "esco:hasLabelRole")
                     :as "roles")
              (concept :via ,(s-prefix "skosxl:altLabel")
                     :inverse t
                     :as "alt-label-of")
              (concept :via ,(s-prefix "skosxl:hiddenLabel")
                     :inverse t
                     :as "hidden-label-of"))
  :has-one `((concept :via ,(s-prefix "skosxl:prefLabel")
                     :inverse t
                     :as "pref-label-of"))
  :on-path "concept-labels"
)

(define-resource label-role ()
  :class (s-prefix "esco:LabelRole")
  :properties `((:preflabel :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://translation.escoportal.eu/labelRole/")
  :features '(no-pagination-defaults)
  :has-many `((concept-label :via ,(s-prefix "esco:hasLabelRole")
                :inverse t
                :as "role-of"))
  :on-path "label-roles")

(define-resource concept-relation ()
  :class (s-prefix "esco:Relationship")
  :properties `((:type :uri-set ,(s-prefix "esco:hasRelationshipType"))
               (:last-modified :string ,(s-prefix "esco:last-modified")))
  :features '(no-pagination-defaults)
  :resource-base (s-url "http://translation.escoportal.eu/relations/")
  :has-one `((concept :via ,(s-prefix "esco:isRelationshipFor")
                    :as "from")
             (concept :via ,(s-prefix "esco:refersConcept")
                    :as "to"))
  :on-path "concept-relations")
